include=~/.config/fuzzel/themes/noctalia

[main]
# Icons
icon-theme=Tela-circle
icons-enabled=yes

# Size
width=45
lines=10
line-height=25

# Padding 
horizontal-pad=40
vertical-pad=20
inner-pad=15

[border]
width=2
radius=15
